export const LangStrings = {
    en: {
        hi: "Hi! I'm Sandra",
        kickass: "I kick ass and take names, and I'm all out of names",
        work_together: "If you want to work with me I'm currently accepting freelance opportunities, so message me at",
        portfolio: "Portfolio",
        previous_work: "Previous work",
        sandras_portfolio: "Sandra's Portfolio",
        all_rights_reserved: "All Rights Reserved",
        about: "About",
        articles: "Articles",
        home: "Home",
        slogan: "An example site showcasing a bilingual site with NextJS.",
    },
    es: {
        hi: "¡Hola! Soy sandra",
        kickass: "Pateo traseros y tomo nombres, y me quedo sin nombres",
        work_together: "Si quieres trabajar conmigo, actualmente estoy aceptando oportunidades independientes, así que envíame un mensaje a",
        portfolio: "Portafolio",
        previous_work: "Trabajo previo",
        sandras_portfolio: "Portafolio de Sandra",
        all_rights_reserved: "Reservados todos los derechos",
        about: "Sobre",
        articles: "Artículos",
        home: "Hogar",
        slogan: "Un sitio de ejemplo que muestra un sitio bilingüe con NextJS.",
    },
    ca: {
        hi: "Hola! Sóc la Sandra",
        kickass: "Pateo el cul i prenc noms, i estic sense noms",
        work_together: "Si vols treballar amb mi, actualment accepto oportunitats d'autònom, així que envia'm un missatge a",
        portfolio: "Cartera",
        previous_work: "Treball previ",
        sandras_portfolio: "Cartera de Sandra",
        all_rights_reserved: "Tots els drets reservats",
        about: "Sobre",
        articles: "Articles",
        home: "A casa",
        slogan: "Un lloc d'exemple que mostra un lloc bilingüe amb NextJS.",
    },
}