export const LangStrings = {
    en: {
        hi: "Hi! I'm Sandra",
        kickass: "I kick ass and take names, and I'm all out of names",
        work_together: "If you want to work with me I'm currently accepting freelance opportunities, so message me at",
        portfolio: "Portfolio",
        previous_work: "Previous work",
        sandras_portfolio: "Sandra's Portfolio",
        all_rights_reserved: "All Rights Reserved",
        cannabis_influencer: "How to become a cannabis influencer",
        cannamyths: "Cannamyths: clearing up myths about cannabis",
        munchies_attack: "Attack of the munchies",
        orgasms: "Cannabis and Orgasms",
        insomnia: "Cannabis and Insomnia",
        about: "About",
        language: "Language",
        dark_mode: "Dark Mode",
        articles: "Articles",
        more: "More",
        resume: "Resume",
        home: "Home",
        slogan: "An example site showcasing a bilingual site with NextJS.",
        thanks_for_reading: "Thanks for reading!",
        role: "Role",
        company: "Company",
        time_frame: 'Time Frame',
        team_style: "Team Style",
        tools: "Tools",
        graphic_designer: "Graphic Designer",
        solo_designer: "Solo Designer",
        construction: "This portfolio is still being built, please pardon our dust!",
        animation: "Animation",
        animator: "Animator",
        illustrator: "Illustrator",
        from_the_archive: "From the Archive",
        lineart: "Lineart Illustrations",
        internship: "Work from my illustration internship",
        coffee: "Redefining brand guidelines for a coffee company",
        zobeida_description: "Illustrations inspired by Las Ciudades Invisibles by Italo Calvino",
        animated_video: "Developing animated promotional videos for SaaS healthcare startup",
        patterns_description: "Patterns I worked on during my illustration internship",
        pattern_designs: "Pattern Designs",
        omonovo_title: "Omonovo animation",
        magazine_title: "Magazine Illustrations",
        magazine_description: "Illustrations for opinion editorials for Sant Cugat",
        sundance: "Sundance Festival",

    },
    es: {
        hi: "¡Hola! Soy Sandra",
        kickass: "Pateo traseros y tomo nombres, y me quedo sin nombres",
        work_together: "Si quieres trabajar conmigo, actualmente estoy aceptando oportunidades independientes, así que envíame un mensaje a",
        portfolio: "Portafolio",
        previous_work: "Trabajo previo",
        sandras_portfolio: "Portafolio de Sandra",
        all_rights_reserved: "Reservados todos los derechos",
        cannabis_influencer: "Cómo convertirte en un influencer de cannabis",
        cannamyths: "Cannamitos: despejando mitos sobre el cannabis",
        munchies_attack: "Ataque de los munchies",
        orgasms: "Cannabis y orgasmos",
        insomnia: "Cannabis e insomnio",
        about: "Sobre",
        language: "Idioma",
        dark_mode: "Modo oscuro",
        articles: "Artículos",
        more: "Más",
        resume: "Currículum",
        home: "Hogar",
        slogan: "Un sitio de ejemplo que muestra un sitio bilingüe con NextJS.",
        thanks_for_reading: "¡Gracias por leer!",
        role: "Rol",
        company: "Compañía",
        time_frame: 'Periodo de tiempo',
        team_style: "Estilo de equipo",
        tools: "Herramientas",
        graphic_designer: "Diseñadora grafica",
        solo_designer: "Diseñadora solista",
        construction: "Esta cartera aún se está construyendo, ¡perdone nuestro polvo!",
        animation: "Animación",
        animator: "Animadora",
        illustrator: "Ilustradora",
        from_the_archive: "Del archivo",
        lineart: "Ilustraciones lineales",
        internship: "Trabajo de mi pasantía de ilustración",
        coffee: "Redefinición de las pautas de marca para una empresa de café",
        zobeida_description: "Ilustraciones inspiradas en Las Ciudades Invisibles de Italo Calvino",
        animated_video: "Desarrollo de videos promocionales animados para startup de salud SaaS",
        patterns_description: "Patrones en los que trabajé durante mi pasantía de ilustración",
        pattern_designs: "Diseños de patrones",
        omonovo_title: "Animación de Omonovo",
        magazine_title: "Revista Ilustraciones",
        magazine_description: "Ilustraciones para editoriales de opinión de Sant Cugat",
        sundance: "Festival de Sundance",

    },
    ca: {
        hi: "Hola! Sóc la Sandra",
        kickass: "Pateo el cul i prenc noms, i estic sense noms",
        work_together: "Si vols treballar amb mi, actualment accepto oportunitats d'autònom, així que envia'm un missatge a",
        portfolio: "Cartera",
        previous_work: "Treball previ",
        sandras_portfolio: "Cartera de Sandra",
        all_rights_reserved: "Tots els drets reservats",
        cannabis_influencer: "Com esdevenir un influencer de cànnabis",
        cannamyths: "Cannamites: aclarint mites sobre el cànnabis",
        munchies_attack: "L'atac dels munchies",
        orgasms: "Cànnabis i orgasmes",
        insomnia: "Cànnabis i insomni",
        about: "Sobre",
        language: "Llenguatge",
        dark_mode: "Mode fosc",
        articles: "Articles",
        more: "Més",
        resume: "Resum",
        home: "A casa",
        slogan: "Un lloc d'exemple que mostra un lloc bilingüe amb NextJS.",
        thanks_for_reading: "Gràcies per llegir!",
        role: "Rol",
        company: "Companyia",
        time_frame: 'Període de temps',
        team_style: "Estil d'equip",
        tools: "Eines",
        graphic_designer: "Dissenyador gràfic",
        solo_designer: "Dissenyador solista",
        construction: "Aquesta cartera encara s'està construint, si us plau, disculpeu la nostra pols!",
        animation: "Animació",
        animator: "Animador",
        illustrator: "Illustrador",
        from_the_archive: "De l'arxiu",
        lineart: "Illustracions Lineart",
        internship: "Treball de les meves pràctiques d'il·lustració",
        coffee: "Redefinició de les directrius de marca per a una empresa de cafè",
        zobeida_description: "Illustracions inspirades en Las Ciudades Invisibles d'Italo Calvino",
        animated_video: "Desenvolupament de vídeos promocionals animats per a l'inici de la sanitat SaaS",
        patterns_description: "Patrons que vaig treballar durant les pràctiques d'il·lustració",
        pattern_designs: "Dissenys de patrons",
        omonovo_title: "Animació Omonovo",
        magazine_title: "Il·lustracions de revistes",
        magazine_description: "Il·lustracions per a editorials d'opinió de Sant Cugat",
        sundance: "Festival de Sundance",

    },
}